### ISSUE TITLE
[Bounty] Add HDR capability

### ISSUE THREAD

**Issue by 5andr0** [5andr0/Virtual-HDR-Display#1]
I'd like to offer a bounty to whoever creates a Windows 10+ Virtual Display Driver with HDR capabilities.
It looks like this is not possible with the indirect display driver (Source: [/MicrosoftDocs/windows-driver-docs-ddi](https://github.com/MicrosoftDocs/windows-driver-docs-ddi/issues/199#issuecomment-424825422))
The driver has to be based on a Kernel mode display-only miniport driver ([KMDOD](https://learn.microsoft.com/en-us/samples/microsoft/windows-driver-samples/kernel-mode-display-only-miniport-driver-kmdod-sample/))
/boss €100

**Comment by pnogemane** [comment]
Is this issue still open?
